
nginx:
  build: ./docker/nginx
  ports:
    - 80:80
  links:
    - node
  container_name: nginx


node:
  build: ./docker/node
  volumes:
    - ./src/server:/usr/src/app
  working_dir: /usr/src/app
  command: sh -c 'npm install; npm start'
  expose:
    - 8080
  container_name: node
